-- V10: No-op migration (constraint already added in V9)
-- This migration was originally created to handle edge cases where V9 might have been executed differently
-- Since V9 correctly adds the UNIQUE constraint on image_token for both H2 and PostgreSQL,
-- this migration is intentionally empty to maintain compatibility with both databases.
--
-- The uk_items_image_token constraint is guaranteed to exist after V9 execution.
